version: '3'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.6.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      rocketmq:
        ipv4_address: 172.23.0.2
        aliases:
          - namesrv

  broker-a:
    image: rocketmqinc/rocketmq:4.6.0
    container_name: rmqbroker-a
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data1/broker/logs:/home/rocketmq/logs
      - ./data1/broker/store:/home/rocketmq/store
      - ./data1/broker/conf/broker-a.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-a.conf
    command: sh mqbroker -c ../conf/broker-a.conf
    networks:
      rocketmq:
        ipv4_address: 172.23.0.3
        aliases:
          - broker-a

  broker-b:
    image: rocketmqinc/rocketmq:4.6.0
    container_name: rmqbroker-b
    links:
      - namesrv
    ports:
      - 20909:10909
      - 20911:10911
      - 20912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data2/broker/logs:/home/rocketmq/logs
      - ./data2/broker/store:/home/rocketmq/store
      - ./data2/broker/conf/broker-b.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-b.conf
    command: sh mqbroker -c ../conf/broker-b.conf
    networks:
      rocketmq:
        ipv4_address: 172.23.0.4
        aliases:
        - broker-b

  broker-a-s:
    image: rocketmqinc/rocketmq:4.6.0
    container_name: rmqbroker-a-s
    links:
      - namesrv
    ports:
      - 30909:10909
      - 30911:10911
      - 30912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data3/broker/logs:/home/rocketmq/logs
      - ./data3/broker/store:/home/rocketmq/store
      - ./data3/broker/conf/broker-a-s.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-a-s.conf
    command: sh mqbroker -c ../conf/broker-a-s.conf
    networks:
      rocketmq:
        ipv4_address: 172.23.0.5
        aliases:
        - broker-a-s

  broker-b-s:
    image: rocketmqinc/rocketmq:4.6.0
    container_name: rmqbroker-b-s
    links:
      - namesrv
    ports:
      - 40909:10909
      - 40911:10911
      - 40912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data4/broker/logs:/home/rocketmq/logs
      - ./data4/broker/store:/home/rocketmq/store
      - ./data4/broker/conf/broker-b-s.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-b-s.conf
    command: sh mqbroker -c ../conf/broker-b-s.conf
    networks:
      rocketmq:
        ipv4_address: 172.23.0.6
        aliases:
        - broker-b-s

  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    links:
      - namesrv
    ports:
      - 8090:8080
    environment:
      - JAVA_OPT=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    command: sh -c java $JAVA_OPT -jar /app.jar
    networks:
      rocketmq:
        ipv4_address: 172.23.0.7
        aliases:
        - rocketmq-console

networks:
  rocketmq:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16