version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.5.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    environment:
      - JAVA_OPTS=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      rocketmq:
        aliases:
          - namesrv

  broker-a:
    image: rocketmqinc/rocketmq:4.5.2
    container_name: rmqbroker-a
    depends_on:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data1/broker/logs:/home/rocketmq/logs
      - ./data1/broker/store:/home/rocketmq/store
      - ./data1/broker/conf/broker-a.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-a.conf
    command: sh mqbroker -c ../conf/broker-a.conf
    networks:
      rocketmq:
        aliases:
          - broker-a

  broker-b:
    image: rocketmqinc/rocketmq:4.5.2
    container_name: rmqbroker-b
    depends_on:
      - namesrv
    ports:
      - 20909:10909
      - 20911:10911
      - 20912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data2/broker/logs:/home/rocketmq/logs
      - ./data2/broker/store:/home/rocketmq/store
      - ./data2/broker/conf/broker-b.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-b.conf
    command: sh mqbroker -c ../conf/broker-b.conf
    networks:
      rocketmq:
        aliases:
          - broker-b

  broker-a-s:
    image: rocketmqinc/rocketmq:4.5.2
    container_name: rmqbroker-a-s
    depends_on:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data3/broker/logs:/home/rocketmq/logs
      - ./data3/broker/store:/home/rocketmq/store
      - ./data3/broker/conf/broker-a-s.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-a-s.conf
    command: sh mqbroker -c ../conf/broker-a-s.conf
    networks:
      rocketmq:
        aliases:
          - broker-a-s

  broker-b-s:
    image: rocketmqinc/rocketmq:4.5.2
    container_name: rmqbroker-b-s
    depends_on:
      - namesrv
    ports:
      - 20909:10909
      - 20911:10911
      - 20912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data4/broker/logs:/home/rocketmq/logs
      - ./data4/broker/store:/home/rocketmq/store
      - ./data4/broker/conf/broker-b-s.conf:/home/rocketmq/rocketmq-4.5.2/conf/broker-b-s.conf
    command: sh mqbroker -c ../conf/broker-b-s.conf
    networks:
      rocketmq:
        aliases:
          - broker-b-s

  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    depends_on:
      - namesrv
    ports:
      - 8090:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    command: sh -c java $JAVA_OPTS -jar /app.jar
    networks:
      rocketmq:
        aliases:
          - rocketmq-console

networks:
  rocketmq:
    name: rocketmq
    driver: bridge